### ISSUE TITLE
[Bug]: 无法安装simhash-py

### ISSUE THREAD

**Issue by AnitaSherry** [alibaba/data-juicer#87]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

Ubuntu

### Installation Method 安装方式

from source

### Python Version Python版本

3.9

### Describe the bug 描述这个bug

  /home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-642i4337/simhash-py_707a16c4f0d24a878223a92ec6376dbd/simhash/simhash.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  import hashlib
  import struct

  from simhash cimport compute as c_compute
  ^
  ------------------------------------------------------------

  simhash/simhash.pyx:4:0: 'simhash/compute.pxd' not found

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  import hashlib
  import struct

  from simhash cimport compute as c_compute
  from simhash cimport find_all as c_find_all
  ^
  ------------------------------------------------------------

  simhash/simhash.pyx:5:0: 'simhash/find_all.pxd' not found

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      Find the set of all matches within the provided vector of hashes.

      The provided hashes are manipulated in place, but upon completion are
      restored to their original state.
      '''
      cdef matches_t results_set = c_find_all(hashes, number_of_blocks, different_bits)
           ^
  ------------------------------------------------------------

  simhash/simhash.pyx:26:9: 'matches_t' is not a type identifier

  Error compiling Cython file:
  ------------------------------------------------------------
  ...

      The provided hashes are manipulated in place, but upon completion are
      restored to their original state.
      '''
      cdef matches_t results_set = c_find_all(hashes, number_of_blocks, different_bits)
      cdef vector[match_t] results_vector
           ^
  ------------------------------------------------------------

  simhash/simhash.pyx:27:9: 'vector' is not a type identifier

  Error compiling Cython file:
  ------------------------------------------------------------
  ...

      The provided hashes are manipulated in place, but upon completion are
      restored to their original state.
      '''
      cdef matches_t results_set = c_find_all(hashes, number_of_blocks, different_bits)
      cdef vector[match_t] results_vector
           ^
  ------------------------------------------------------------

  simhash/simhash.pyx:27:9: 'vector' is not a type identifier

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      # Unpacks the binary bytes in digest into a Python integer
      return struct.unpack('>Q', digest)[0] & 0xFFFFFFFFFFFFFFFF

  def compute(hashes):
      '''Compute the simhash of a vector of hashes.'''
      return c_compute(hashes)
             ^
  ------------------------------------------------------------

  simhash/simhash.pyx:17:11: 'c_compute' is not a constant, variable or function identifier

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      Find the set of all matches within the provided vector of hashes.

      The provided hashes are manipulated in place, but upon completion are
      restored to their original state.
      '''
      cdef matches_t results_set = c_find_all(hashes, number_of_blocks, different_bits)
                                   ^
  ------------------------------------------------------------

  simhash/simhash.pyx:26:33: 'c_find_all' is not a constant, variable or function identifier
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/tmp/pip-install-642i4337/simhash-py_707a16c4f0d24a878223a92ec6376dbd/setup.py", line 38, in <module>
      setup(
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
      self.run_command("build")
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
      new_ext = cythonize(
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
      cythonize_one(*args)
    File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: simhash/simhash.pyx
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/kemove/anaconda3/envs/sakura/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-642i4337/simhash-py_707a16c4f0d24a878223a92ec6376dbd/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /tmp/pip-wheel-oyoenh4d
  cwd: /tmp/pip-install-642i4337/simhash-py_707a16c4f0d24a878223a92ec6376dbd/
  Building wheel for simhash-py (setup.py) ... error
  ERROR: Failed building wheel for simhash-py
  Running setup.py clean for simhash-py
  Running command python setup.py clean
  Building from Cython
  /home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running clean
  removing 'build/lib.linux-x86_64-3.9' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.9' does not exist -- can't clean it
Failed to build simhash-py
ERROR: Could not build wheels for simhash-py, which is required to install pyproject.toml-based projects
WARNING: There was an error checking the latest version of pip.

### To Reproduce 如何复现

cd data-juicer
pip install -v -e .

**Comment by fuxuelinwudi** [comment]
conda环境装python=3.8 可以解决

**Comment by HYLcool** [comment]
@AnitaSherry 你好，感谢你的关注与使用！

由于simhash库本身支持的问题，它的原始代码库只能安装并使用于python3.8及以下的环境，因此目前你有两种方法来解决其安装失败的问题：
1. 使用一个符合要求的python环境：如 @fuxuelinwudi 提供的方法，感谢 @fuxuelinwudi 提供帮助！
2. 从源码安装，并将simhash-py的安装源从原始代码库改为 https://github.com/hylcool/simhash-py ，后者是我们基于原代码库做了若干修改，使得它能够兼容python 3.9及以上的版本

供你参考~如有进一步问题欢迎随时提问

**Comment by AnitaSherry** [comment]
从 https://github.com/hylcool/simhash-py 源码安装也失败。
`
(sakura) kemove@kemove-Super-Server:/data/competition/competition_kit/data-juicer/simhash-py-master$ pip install .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /data/competition/competition_kit/data-juicer/simhash-py-master
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simhash-py
  Building wheel for simhash-py (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [108 lines of output]
      Building from Cython
      /home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/simhash
      copying simhash/__init__.py -> build/lib.linux-x86_64-3.9/simhash
      running build_ext
      Compiling simhash/simhash.pyx because it changed.
      [1/1] Cythonizing simhash/simhash.pyx
      /home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /data/competition/competition_kit/data-juicer/simhash-py-master/simhash/simhash.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import hashlib
      import struct
      
      from simhash cimport compute as c_compute
      ^
      ------------------------------------------------------------
      
      simhash/simhash.pyx:4:0: 'simhash/compute.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import hashlib
      import struct
      
      from simhash cimport compute as c_compute
      from simhash cimport find_all as c_find_all
      ^
      ------------------------------------------------------------
      
      simhash/simhash.pyx:5:0: 'simhash/find_all.pxd' not found
      warning: simhash/simhash.pyx:15:0: Overriding cdef method with def method.
      warning: simhash/simhash.pyx:19:0: Overriding cdef method with def method.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          # Unpacks the binary bytes in digest into a Python integer
          return struct.unpack('>Q', digest)[0] & 0xFFFFFFFFFFFFFFFF
      
      def compute(hashes):
          '''Compute the simhash of a vector of hashes.'''
          return c_compute(hashes)
                 ^
      ------------------------------------------------------------
      
      simhash/simhash.pyx:17:11: 'c_compute' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          Find the set of all matches within the provided vector of hashes.
      
          The provided hashes are manipulated in place, but upon completion are
          restored to their original state.
          '''
          cdef matches_t results_set = c_find_all(hashes, number_of_blocks, different_bits)
                                       ^
      ------------------------------------------------------------
      
      simhash/simhash.pyx:26:33: 'c_find_all' is not a constant, variable or function identifier
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/competition/competition_kit/data-juicer/simhash-py-master/setup.py", line 37, in <module>
          setup(
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/home/kemove/anaconda3/envs/sakura/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: simhash/simhash.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simhash-py
  Running setup.py clean for simhash-py
Failed to build simhash-py
ERROR: Could not build wheels for simhash-py, which is required to install pyproject.toml-based projects
WARNING: There was an error checking the latest version of pip.
`

**Comment by AnitaSherry** [comment]
现在很多项目都要用到python3.11了，这怎么还停留在python3.8，这样太过时了

**Comment by AnitaSherry** [comment]
在environments/science_requires.txt中
删掉simhash-py，变成simhash，就成功安装了

**Comment by HYLcool** [comment]
> 现在很多项目都要用到python3.11了，这怎么还停留在python3.8，这样太过时了

这种第三方库的原因我们这边目前也没啥好的办法，作者对这个库已经不做后续支持了。。。后边儿我们会考虑看能否替换为别的依赖库或者我们自行实现这一套计算过程吧

**Comment by liuyukid** [comment]
我之前也遇到过这个问题，可以试试把Cython的版本降低一点试试，我用Cython==0.29.21之后就可以安装simhash-py
